---
apiVersion: v1
kind: Namespace
metadata:
  name: runtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: runtime
spec: 
  replicas: 3
  selector:
    matchLabels: 
      app: apache
  template:
    metadata:
      labels: 
        app: apache
    spec:
      containers:
      - image: hyhxy0206/apache:v1
        imagePullPolicy: IfNotPresent
        name: httpd
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: runtime
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: apache
  type: NodePort

